Build docker images with maven-docker-plugin (#4)
* build docker images with maven-docker-plugin, run containers in integration test phase

* set version to 0-SNAPSHOT, version is set during build

* increase timeouts for containers

* update base image to eclipse-temurin:17-jre

* possible fix to resolve 2 existing beans issue

* still have to fix 2 beans issues

* remove added stuff

* disable docker run for now during integration test phase

* remove version in maven command

* fix push command

* trigger a build

* enable multi-arch builds

* use eclipse-temurin:17-jre-jammy as base-image

* try out zulu with github-actions

* update maven-docker-plugin version, try matrix-build

* try more, set 'fail-fast' to false to run complete matrix

* try with separate config class

* set autoconfigure_before to another position

* make config class public

* try to resolve searchParamRegistry issue

* back to temurin, no matrix-build, push image if successfull

* add structure-definition 'QuelleKlinischesBezugsdatum' in /profiles folder

* fix docker image startup

* setup db with script to start successfully

diff --git a/.github/workflows/build-features.yaml b/.github/workflows/build-features.yaml
--- a/.github/workflows/build-features.yaml
+++ b/.github/workflows/build-features.yaml
@@ -16,6 +16,11 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        java: ['11','17']
+#        distribution: ['temurin','zulu', 'adopt', 'oracle']
 
     steps:
       - name: Checkout
@@ -30,5 +35,39 @@ jobs:
           java-version: '17'
           cache: 'maven'
 
-      - name: Build Docker image
-        run: ./mvnw spring-boot:build-image
+      - name: Set some variables for the build
+        run: |
+          if [ ${{ github.ref }} != 'refs/heads/num-main' ]; then
+            echo "IS NOT num-main branch"
+            echo "BUILD_VERSION=1.5.5-$GITHUB_RUN_NUMBER-PR" >> $GITHUB_ENV
+          else
+            echo "IS main branch"
+            echo "BUILD_VERSION=1.5.5-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
+          fi
+        shell: bash
+
+      - name: See some values
+        run: |
+          echo "GITHUB_REF=$GITHUB_REF"
+          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
+          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
+          echo "BUILD_VERSION=$BUILD_VERSION"
+
+      - name: Echo Env Vars through Context
+        run: |
+          echo "$GITHUB_CONTEXT"
+
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Set Build-Version in pom.xml
+        run: ./mvnw versions:set -DnewVersion=$BUILD_VERSION
+
+      - name: Build project with Maven
+        run: ./mvnw verify
+
+      - name: Docker push image
+        run: ./mvnw io.fabric8:docker-maven-plugin:push
